#!/bin/bash

STARTTIME=`date +%s`
printf "\n$(date +%T) Pre-push starting\n"

command_exists() {
  command -v "$1" >/dev/null 2>&1;
}

unstash_and_exit() {
  STASHES=$(git stash list | grep "$STASH_NAME")
  if [ "$STASHES" ]; then
    printf "\nUnstashing files...\n"
    git stash pop -q
  fi
  exit $1
}

printf "\nStashing...\n"
STASH_NAME="pre-push-$(date +%s)"
git stash save -q --include-untracked $STASH_NAME

EMDTIME=`date +%s`
printf "\n$(date +%T) Pre-push done,it took $((EMDTIME-STARTTIME)) seconds\n"